### ISSUE TITLE
tool for autogen gazebo plugin

### ISSUE THREAD

**Issue by ivoysey** [cmu-mars/issues#10]
do we need a tool that takes whatever xml representation of the function we're learning for the battery model and produces a version of https://github.com/cmu-mars/brass-energy-monitor for that mathematical function?

**Comment by pooyanjamshidi** [comment]
I think so, in other words, we need a generic discharge module that we can plugin different functions?

**Comment by ivoysey** [comment]
I'm not sure what you mean. What I meant was a piece of code that parses your XML file and writes a gazebo plugin in C++ per function.

**Comment by ivoysey** [comment]
deprecated
