### ISSUE TITLE
add event based logging

### ISSUE THREAD

**Issue by ivoysey** [cmu-mars/issues#101]
something like
```
[{"event" : "start", "location" : {"x" : 1, "y" : 2}, "time" : 45},
 {"event" : "waypoint", "location" : {"x": "2", "y" : 2}, "time": 50},
 {"event" : "nodefail", "location" : {"x" : 2, "y": 2.4}, "time" : 55, "node" : "amcl},
 {"event" : "waypoint", "location" : {"x": 2, "y" : 3}, "time" : 60}, ...]
```
in a file after each run

one possible approach is to store this in a list in `config` and update it based on topics or listening to the IG interpreter, then dump it to the file system before sending a done or an error. this saves file system IO time but may not produce a log in all tests.

another approach is to just append to a file every time something of this form comes up. which always works but may be costly.

**Comment by pooyanjamshidi** [comment]
@ivoysey interesting! but maybe TH will produce this already, probably ask LL whether this is an option. This is also related to `CP1`.

**Comment by ivoysey** [comment]
@pooyanjamshidi The TH definitely does not produce this already.

In your case we produce something a little bit similar -- which is that we have a data structure of when the SUT reports to the TA that it's at *one of the waypoints in the mission*, but not any waypoint at all. So if you have a mission `l1 l3 l4 l2` then we get to know when you're at `l1` and `l3` but if the plan for how to get there goes through `l5` and `l6` we don't know about those things.

**Comment by pooyanjamshidi** [comment]
@ivoysey on the second thought, cannot we generate this automatically from the information in `access.log`? all events are logged there.

**Comment by ivoysey** [comment]
@pooyanjamshidi Yeah, it's derivable but probably kind of a hassle. This is more of a convenience than a real necessity.

**Comment by schmerl** [comment]
I don't think this comes from access.log, because not all the information is reported in status, observations, or other calls to the TA. Some of it is, for sure.

**Comment by schmerl** [comment]
@ivoysey Where are we on this?

**Comment by ivoysey** [comment]
I think this is derivable from the other logs, and we're out of time.
