### ISSUE TITLE
Exception in TA on observe

### ISSUE THREAD

**Issue by schmerl** [cmu-mars/issues#106]
This happens only sometimes, perhaps as a race condition, perhaps because my TH calls observe too early:

```
[flask.app][ERROR] 2018-06-12 16:13:01,169: Exception on /observe [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2292, in wsgi
_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1815, in full
_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1718, in hand
le_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 35, in re
raise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1813, in full
_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1799, in disp
atch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/dist-packages/connexion/decorators/decorator.py
", line 66, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.5/dist-packages/connexion/decorators/decorator.py
", line 42, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.5/dist-packages/connexion/decorators/parameter.py
", line 195, in wrapper
    return function(**kwargs)
  File "/usr/src/app/swagger_server/controllers/default_controller.py", line 147
, in observe_get
    ret.battery = config.battery
  File "/usr/src/app/swagger_server/models/inline_response2003.py", line 135, in
 battery
    raise ValueError("Invalid value for `battery`, must not be `None`")
ValueError: Invalid value for `battery`, must not be `None`
```

**Comment by ivoysey** [comment]
@schmerl This is happening because `/observe` is getting hit before the callback for the `energy_level` topic is run for the first time (https://github.mit.edu/brass/cmu-robotics/blob/master/cp3/ta/swagger_server/__main__.py#L199). So the value of `config.battery` is still `None`, which is not an integer, so the generated code from the Swagger spec is stopping us from returning it because it's not to spec.

I think the `ValueError` is actually correct in that it's stopping us from sending back garbage to the requester. The actual problem is that `/observe` is getting called too early. Can you tell me more about how that's happening?

**Comment by schmerl** [comment]
My TH is very simple at the moment, and so I think it probably voids the state machine. I wait for the ready message to be processed and then I start two threads: One thread wait for live and then calls start and then waits for some time and perturbs; the other thread starts and calls observe every second until the done message appears. I'm pretty sure that what is happening is that I could be calling observe even before live gets posted. So, I think that is my fault, thinking through it now.  Let me do some code changes to synch my threads better and then report it if I see it again.

**Comment by ivoysey** [comment]
Yeah -- that's the kind of sequence diagram stuff I was worried about when we talked yesterday. You actually shouldn't hit `/observe` until you get a response from having hit `/start`.

There's a small chance that another thing is happening, which is that ROS could be publishing non-numerical values to the topic. I think that's pretty unlikely. If we see this again and we think the sequence diagram is being respected, I'll add some code to the call back to check what we're actually getting.
