### ISSUE TITLE
Rainbow failed when placing obstacle

### ISSUE THREAD

**Issue by pooyanjamshidi** [cmu-mars/issues#112]
This exception happened when I put an obstacle.
```
curl -X POST "http://0.0.0.0:8080/start" -H "accept: application/json"
curl -X POST "http://0.0.0.0:8080/perturb/place-obstacle" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"x\": -19.08, \"y\": 11.08}"
```

[commnad_line-newc3.log](https://github.com/cmu-mars/issues/files/2168047/commnad_line-newc3.log)
[rainbow-analyzers.log](https://github.com/cmu-mars/issues/files/2168045/rainbow-analyzers.log)
[rainbow-logging.log](https://github.com/cmu-mars/issues/files/2168046/rainbow-logging.log)

**Comment by pooyanjamshidi** [comment]
This might be related to recent changes happened to the rainbow, I never saw this before.

**Comment by schmerl** [comment]
@pooyanjamshidi Is this happening all the time now? It seems like it is an error with the construction of the prism file. Can you pull out all the files from /home/mars/das/rainbow-brass/targets/brass-p2-cp1/prism and post them here?

**Comment by schmerl** [comment]
OK, so Rainbow has hardwired into it a battery capacity (in CP1) of 32560.0. Somewhere you are trying to set it to be 32822, which is greater. I'm not sure of the semantics here so @pooyanjamshidi @javier-camara   you guys need to figure this out.

This is what I get from this line in the output:
`Error: Invalid initial value (32823) for variable "b" (line 103, column 1).`, 

and when I look at SimpleConfigurationBatteryModel.java on the line:
`	public static Double m_battery_capacity=32560.0;`
No-one  seems to calling:
```java
	public static void setBatteryCapacity(Double m_battery_capacity) {
		SimpleConfigurationBatteryModel.m_battery_capacity = m_battery_capacity;
	}
```

Should this come from a configuration file?

**Comment by pooyanjamshidi** [comment]
@javier-camara @schmerl I still get the same error.
[prism.txt](https://github.com/cmu-mars/issues/files/2171877/prism.txt)

[rainbow-analyzers.log](https://github.com/cmu-mars/issues/files/2171881/rainbow-analyzers.log)
[rainbow-logging.log](https://github.com/cmu-mars/issues/files/2171882/rainbow-logging.log)

**Comment by schmerl** [comment]
I do not see the exception.

**Comment by pooyanjamshidi** [comment]
[commnad_line-newc4.log](https://github.com/cmu-mars/issues/files/2171931/commnad_line-newc4.log)

**Comment by pooyanjamshidi** [comment]
This is now fixed.
