### ISSUE TITLE
Update Turtlebot model to have a headlamp

### ISSUE THREAD

**Issue by schmerl** [cmu-mars/issues#21]
Update the gazebo model for turtlebot to include a headlamp.

**Comment by schmerl** [comment]
The first prototype for this is in: https://github.com/Ashutoshp/Gazebo-Light-Plugin.

**Comment by ivoysey** [comment]
also relevant to https://github.mit.edu/brass/cmu-robotics/issues/48

**Comment by schmerl** [comment]
This is working with Gazebo 7.8, just need to have it integrated with the bigger code base.

**Comment by schmerl** [comment]
See: https://github.com/cmu-mars/cp3_base/tree/develop
