### ISSUE TITLE
Self-adaptive planning scenario

### ISSUE THREAD

**Issue by schmerl** [cmu-mars/issues#26]
Assuming that we have different algorithms, sensors, etc. working, develop and example of the planner coming up with a new plan (not integrated with the actual system).

Prerequisites:

1. Mission, Robot State
2. Architecture of the current system
3. Rules for what a correct architecture is
4. Impact of tactics on the qualities of the system (accuracy, timeliness, safety, efficiency)

**Comment by ivoysey** [comment]
defunct / done
