### ISSUE TITLE
Place markers on the map

### ISSUE THREAD

**Issue by schmerl** [cmu-mars/issues#28]
Visual markers need to be placed on the map in a way that means the robot can always see at least one marker! We probably want to do this with code, using the mapeditor and the utilities that generate the world. Some complicating factors:

1. The markers should be placed high enough so that they are above any low obstacles we also place in the  map
2. The markers need to be placed on a walls (I think) to avoid collisions, facing into the corridors. This means when specifying the marker placement, we need to know/specify which side of the wall it is going to be on.

**Comment by javier-camara** [comment]
Should this issue be closed? I believe that you are already doing this via code, right?

**Comment by schmerl** [comment]
This has now been changed to be done automatically by a script in utils.
