### ISSUE TITLE
Regenerate time estimates for CP3

### ISSUE THREAD

**Issue by schmerl** [cmu-mars/issues#30]
The time estimates for paths need to be regenerated using a new timing model.

**Comment by schmerl** [comment]
I'm putting this issue in as a reminder that we need to make sure to redo this close to the deadline for evaluation.

The issue is that we made need different estimates for each configuration of the robot, for each path, but we should discuss this at some point. 

Also, we might want to set up some experiments on gazebo for learning this experimentally with Gazebo.

**Comment by bisc** [comment]
Do you mean experiments similar to those Rajat did, but with a newer version of Gazebo?

**Comment by schmerl** [comment]
Unfortunately, yes.

**Comment by bisc** [comment]
Hopefully it would be sufficient to calibrate the expected time with a constant multiplier if needed.

**Comment by bisc** [comment]
This issue may refine/extend the timing model from here: https://github.com/cmu-mars/motion-timing

**Comment by ivoysey** [comment]
I'm moving this to RR2 IW.

**Comment by ivoysey** [comment]
@schmerl @bisc What's the status of this? Do we still need to do it?

**Comment by bisc** [comment]
It hasn't been done. I don't know whether anything happened that would invalidate this task.

**Comment by schmerl** [comment]
It will be done before code freeze. This is just a reminder for be to do
it.
