### ISSUE TITLE
Script for configuration id

### ISSUE THREAD

**Issue by pooyanjamshidi** [cmu-mars/issues#33]
@schmerl I forgot what exactly I needed to do for this, can you please let me know what was this? my poor memory!

**Comment by schmerl** [comment]
You need a script that prints the configuration id of the robot to stdout, I think.

**Comment by pooyanjamshidi** [comment]
The [probe](https://github.com/cmu-mars/cp1_controllers/tree/master/scripts) is done. @schmerl would you please check if this is OK?

**Comment by pooyanjamshidi** [comment]
@schmerl I presume this was OK so I'll close the issue, reopen it if you think something is missing.
