### ISSUE TITLE
Update battery plugin to write charge level to topic

### ISSUE THREAD

**Issue by pooyanjamshidi** [cmu-mars/issues#34]

**Comment by pooyanjamshidi** [comment]
The battery charge is written to the following topic: `/mobile_base/commands/charge_level`. @schmerl is that OK?

**Comment by schmerl** [comment]
Sure. You'r saying it does this now?

**Comment by pooyanjamshidi** [comment]
Yes, it now publishes to the [topic](https://github.com/cmu-mars/brass_gazebo_battery/blob/0aeba9e53a7ccedf614de0968cf9ba81fe187555/src/battery_discharge.cpp#L79). I'm going to close this issue then.

**Comment by schmerl** [comment]
@pooyanjamshidi Does this just report a Float64, or some other format for the message?

**Comment by pooyanjamshidi** [comment]
`std_msgs::Float64`
