### ISSUE TITLE
Model/Gauges for config id

### ISSUE THREAD

**Issue by pooyanjamshidi** [cmu-mars/issues#35]

**Comment by schmerl** [comment]
This is in: https://github.com/cmu-able/rainbow/tree/develop/deployments/rainbow-brass/src/main/java/org/sa/rainbow/brass/model/p2_cp1/robot and https://github.com/cmu-able/rainbow/tree/develop/deployments/rainbow-brass/src/main/java/org/sa/rainbow/brass/gauges/p2_cp1
