### ISSUE TITLE
Power analyzer for rainbow

### ISSUE THREAD

**Issue by pooyanjamshidi** [cmu-mars/issues#36]
Write an analyzer for Rainbow that takes current configuration of the robot, its current charge, and rest of actions that need to accomplish and then determine whether the action can be accomplished given the current charge or not.

**Comment by schmerl** [comment]
@javier-camara Can you remind me what this is for? Don't we have something like this already in the planner?

**Comment by javier-camara** [comment]
This is an analyzer similar to the one we had in Phase 1 to determine if there is enough energy to complete the rest of the mission (although there are of course minor differences). Expanding a bit Pooyan's text: "Write an analyzer that takes current configuration of the robot, its current battery charge, and rest of actions that need to accomplished to complete the task, and then determine whether the remainder of the task can be accomplished (i.e., determine if the current battery charge is greater or equal to the energy required to complete the remaining tasks).

**Comment by javier-camara** [comment]
Sorry, I was reading this again, and I need to make some corrections:  "Write an analyzer that takes the current configuration of the robot, its current battery charge, and rest of actions that need to accomplished to complete the task, and then determine whether the remainder of the task can be accomplished (i.e., determine if the current battery charge is greater or equal to the energy required to complete the remaining *actions in the task*)".

**Comment by miguelvelezmj25** [comment]
The code with this functionality is [here](https://github.com/cmu-mars/ph2-cp1-energy-consumption).

**Comment by schmerl** [comment]
Thanks. Looks like it is not completely implemented? (The method that we
need that takes the time and the config throws an exception by default?)

**Comment by miguelvelezmj25** [comment]
That is what I wanted to talk about today. The path to define where the config file is to get the configuration and power load is declared "final" in the jar file you sent me. So, I cannot change it. That is why the I added the other method that takes the power load and time. Once I can change the path, I can implement my own class to read the config file. However, the general functionality should be working.

**Comment by schmerl** [comment]
OK. I think that is what the other file (which you've left empty) is meant
to be for. In any case, you might want to connect with Javier on this.

**Comment by pooyanjamshidi** [comment]
As a note to @javier-camara and @miguelvelezmj25: the list of config file should live at `~/cp1/config_list.json`. So the model-learner dumps the list in that path and it is where the planner should find it.

**Comment by miguelvelezmj25** [comment]
As discussed today, I will duplicate the necessary classes to test my code and remove the throwing of the exception.

**Comment by miguelvelezmj25** [comment]
I have duplicated the necessary classes and tested the functionality.

The latest commit is located [here](https://github.com/cmu-mars/ph2-cp1-energy-consumption/tree/6cb1a96f42ad4a143d9bc1fc1426682dfe41f7af).
