### ISSUE TITLE
Finalize the planner for CP1

### ISSUE THREAD

**Issue by pooyanjamshidi** [cmu-mars/issues#37]

**Comment by javier-camara** [comment]
Working on this now. Pooyan, could you please send me the map you are going to use for CP1? I'd like to run some tests. Thanks.

**Comment by pooyanjamshidi** [comment]
We are now using this map for our experiments: https://github.com/cmu-mars/cp1_base/blob/master/maps/cp1_map.json
But we might change it after we do our experiments depending on the results.

**Comment by javier-camara** [comment]
This is now done in the terms discussed (objective function is a weighted linear combination of remaining energy maximization and time minimization terms). Tested on the map in 
https://github.com/cmu-mars/cp1_base/blob/master/maps/cp1_map.json

**Comment by pooyanjamshidi** [comment]
Thanks, I presume it's not tight to the map? so we can change the map later?
