### ISSUE TITLE
Add reconfig logic for IG

### ISSUE THREAD

**Issue by pooyanjamshidi** [cmu-mars/issues#38]

**Comment by schmerl** [comment]
I started this. I am envisaging four new instructions (1 for cp1 and 3 for cp3):

**cp1:** SetCP1Config(string)
**cp3:**

- StartNodes(["aruco"|"amcl"|"mrpt"])
- KillNodes(["aruco"| "amcl"| "mrpt"])
- SetSensor(["lidar"|"kinect"|"cameras"|"headlamp"], ["on"|"off"|"True"|"true"|"False"|"false"])

**Comment by schmerl** [comment]
@pooyanjamshidi I will let you write the code for CP1. I'll point you to the file when I think I am ready to have you do it.

**Comment by pooyanjamshidi** [comment]
@schmerl is there any update about this?

**Comment by schmerl** [comment]
No. As I mentioned above, I need you to write the code that will be the backend for this and actually do the reconfiguration in your system For my part, I have added a new instruction called:

SetCP1Config(string) 

That will take a configuration id from your power model JSON file. The IG mechanics should all be in place, but I need you to write the python code to actually set it in your system. See https://github.com/cmu-mars/ig-action-server-p15/blob/master/ig_action_server/src/cp1_instructions.py, which currently throws a Not Implemented exception.

**Comment by schmerl** [comment]
^^^^ @pooyanjamshidi

**Comment by pooyanjamshidi** [comment]
@schmerl done, please check [cp1_instructions.py](https://github.com/cmu-mars/ig-action-server-p15/blob/master/ig_action_server/src/cp1_instructions.py).

**Comment by ivoysey** [comment]
I'm moving this to RR2 IW.

**Comment by pooyanjamshidi** [comment]
This is already done, so I'm closing this.

**Comment by schmerl** [comment]
Hasn't been tested yet so let's reopen.
