### ISSUE TITLE
Mission sequencer API for Rainbow

### ISSUE THREAD

**Issue by pooyanjamshidi** [cmu-mars/issues#40]

**Comment by pooyanjamshidi** [comment]
@schmerl I presume we need to have a way to identify when a task is finished so we can proceed to initiate the subsequent task. The way how we do it for baseline A and B is that we have a [loop](https://github.com/cmu-mars/cp1_controllers/blob/master/src/bot_controller.py#L109) that sequentially runs the tasks and wait until the instruction server execute the igcode and tell us whether it succeed or not.

**Comment by schmerl** [comment]
No need to @ me - I think I get updated on this automatically because I am assigned to this task.

Remind me again what needs to be done in Rainbow? It won't be executing this loop, right? I can't quite remember what we discussed about it a couple of weeks ago (too many intervening task before getting to this one), and the description you provided about the task doesn't really help me remember :-)

**Comment by schmerl** [comment]
@pooyanjamshidi Perhaps we do need to @ each other. See above.

**Comment by pooyanjamshidi** [comment]
@schmerl As far as I remember, Rainbow needs to indicate somewhere (in a shared file or something) that it is done with the current task (whether it successfully accomplished the task or it gave up after some predefined number of attempts). So the code that keeps track of executing the tasks will go ahead with the next task. 

So now something is not clear to me (because of lack of understanding Rainbow): in baseline A and B, we send the igcode associated with each task to the igserver. For baseline C, as far as I understood, we should do the same and Rainbow will intercept the igcode from igserver? or we should explicitly tell rainbow what is the task?

**Comment by schmerl** [comment]
@pooyanjamshidi  Ah, ok, that makes sense. Then this is how I think things should work.

For each task in the mission:
1. The sequencer should indicate the target waypoint for that task is (Rainbow will need to know this for replanning)
2. The sequencer should pass the start instruction graph for that task to the ig_interpreter. 
3. Rainbow should indicate when it thinks it is done with the task

2 should automatically be picked up by Rainbow.

For 1, Rainbow currently gets the target waypoint from a file (in phase 1 and for challenge problem 3 this file is written by the TA). In this CP would should designate a file that will be written to when the target waypoint changes. If you're agreeable, why don't we just write this to the file '~/current-target-waypoint'?

For 3,  could you write a shell script that will tell the missions sequencer that a task in finished, I can hook that into Rainbow as an effector or some such to call when Rainbow thinks it is done with a task.

Does this make sense?

**Comment by pooyanjamshidi** [comment]
@schmerl yeah, they make sense, for 1 how about writing it to `~/cp1/current-target-waypoint` since I have some other shared file like `cp1/config_list.json` that the @javier-camara planner needs?

**Comment by schmerl** [comment]
OK. That makes sense.

**Comment by schmerl** [comment]
I have just checked a prototype probe into the develop branch of rainbow-brass (currently untested).

Will integrate an effector and associated actions in Rainbow when Pooyan delivers the script for saying when a task is done.

**Comment by pooyanjamshidi** [comment]
@schmerl is this shell [script](https://github.com/cmu-mars/cp1_controllers/blob/master/scripts/current_task_finished.sh) OK for item 3 above?

**Comment by schmerl** [comment]
Do you want to know whether we FAILED? Do you want to know what task we
think we finished? If not, then this is ok.

**Comment by pooyanjamshidi** [comment]
Good, revised it and added the FAILED case via an argument.
