### ISSUE TITLE
No gauge for robot speed

### ISSUE THREAD

**Issue by schmerl** [cmu-mars/issues#42]
Need to add a probe and update RobotStateGauge for CP1 and CP3 to include speed of the robot.

**Comment by schmerl** [comment]
@pooyanjamshidi @javier-camara  Do you need to robot speed for anything in CP1?

**Comment by pooyanjamshidi** [comment]
I'm not sure I understand the question, in CP1 we may have a different speed for each configuration, so when the configuration changes the robot speed needs to be changed.

**Comment by schmerl** [comment]
Is there any reason in CP 1 why there adaptive system would need to know
the speed of the robot for analysis or planning?

**Comment by javier-camara** [comment]
I am not sure that the adaptive system needs to monitor speed at runtime. For planning purposes, we need to know the speed of the robot, which is given by config_list.json. For analysis, we also need the battery consumed in the remaining task actions, which indeed depends again on speed (which determines the amount of time that we are discharging the battery). However, that speed is also provided by the json file.

**Comment by schmerl** [comment]
OK.  This has been done for CP3, and so I will mark this as done.
