### ISSUE TITLE
Do testing on Amazon cloud

### ISSUE THREAD

**Issue by schmerl** [cmu-mars/issues#45]
We need to do our own testing on Amazon AWS, not wait for LL to get around to it. This involves someone working out how to deploy our docker images there, and how to manage the funding/cost associated with doing this (because we probably can't use the free tier due to required machine size).

**Comment by ivoysey** [comment]
@schmerl @joshsunshine how do y'all feel about this issue? i know bradley's been doing some testing on his own pretty extensively at least.
