### ISSUE TITLE
New Plan to Instruction Graph interpreter

### ISSUE THREAD

**Issue by schmerl** [cmu-mars/issues#46]
Take advantage of the new instructions in the IG interpreter

**Comment by ivoysey** [comment]
@schmerl is this done?

**Comment by ivoysey** [comment]
I'm moving this to RR2 IW.

**Comment by schmerl** [comment]
This is done for CP3. For Cp1, the instructions have been written but not tested.

**Comment by schmerl** [comment]
Now tested for CP1
