### ISSUE TITLE
write swagger file describing internal status end point

### ISSUE THREAD

**Issue by ivoysey** [cmu-mars/issues#48]
`/internal`

**Comment by schmerl** [comment]
I have an initial version defined [here](https://github.mit.edu/brass/cmu-robotics/blob/development/documents/swagger-yaml/cp3-internal.yml).

**Comment by ivoysey** [comment]
@schmerl OK, that looks good to me. I'll use that to make an internal status endpoint at that name running on the TA, so you can work assuming such a thing exists. I am not totally positive how you'll know what address the TA is running on though? It might just be localhost from the point of view of the DAS because they're not getting composed together any more.

**Comment by schmerl** [comment]
I think internally we know both the host and port.

**Comment by pooyanjamshidi** [comment]
Here is the cp1 [swagger](https://github.com/cmu-mars/cp1_controllers/blob/master/swagger/cp1-internal.yaml) for `/internal`. @ivoysey please check.

**Comment by ivoysey** [comment]
@pooyanjamshidi  I'm going to move this to the same place that Bradley has his, which is in the cmu-robotics repo with the other swagger files. I'm also going to clean it up just a little bit. I'll let you know when I've done that, and I'll delete the copy here so. It's easier if all the swagger files are in exactly one place.

**Comment by ivoysey** [comment]
@pooyanjamshidi OK; I've updated the cp1 repo to remove the file and added it to https://github.mit.edu/brass/cmu-robotics/blob/development/documents/swagger-yaml/cp1-internal.yaml instead.

**Comment by schmerl** [comment]
For mine, I think we need some flexibility in the internal status enum -- I
discovered another one that would be useful yesterday. Maybe we could just
change it to a string and enumerate the valid values in the comments, to
avoid lots of regeneration? Or doesn't that part matter to much because it
is just an object?

**Comment by ivoysey** [comment]
@schmerl I think it's a trade off. It's more regeneration, but also more information to localize errors in a stack trace if something goes wrong. I haven't done a ton with the output of codegen for the internal endpoints just yet, but I *think* it won't be that terrible to update if they change.

**Comment by ivoysey** [comment]
The more I think about it the more I think I'd rather try dealing with codegen. Not using enums is really against the spirit of the tool; it feels like something that might save time in the short term but bite us eventually.

**Comment by ivoysey** [comment]
This has been done and is either integrated into the TA or in the process of being integrated into the TA.
