### ISSUE TITLE
CP3 Sensor and Config listener

### ISSUE THREAD

**Issue by schmerl** [cmu-mars/issues#49]
For RR2, there needs to be a listener implemented that tells the TA when the set of sensors or the configuration changes. There are two options for this:

1. Communicate this from Rainbow that will know what configuration and sensor is planned. Downsides:

    a. Rainbow only knows what is planned not what actually happens
    b. Rainbow doesn't know when the configuration occurs

2. Add code to CP3.py that will call back when the configuration changes. This will cause the TA to send a status of Adapted with the new config and sensors. Complications:

    a. The reconfigurations come in batches of multiple instructions, meaning that we don't really know when we have finished. For example, in the IG we might have the following: `SetSensor(KINECT, off)::SetSensor(HEADLAMP, on)::KillNodes(amcl)::StartNodes(aruco).`
     We want to be able to send the new status after the last StartNodes instruction.
      b. Other things are based on ground truth (i.e., getting the truth from gazebo). The approach outlined here is what the DAS thinks the robot's configuration is, not what it actually is. The problem about when we know reconfiguration has ended becomes much harder if we are trying to get this from gazebo and ros.

**Comment by schmerl** [comment]
Moved to RR3 because it is really about evaluation.

**Comment by schmerl** [comment]
Is the intent here that the config, path, and sensor informattion are sent as a status message or with observe?

**Comment by schmerl** [comment]
I think this is done.

**Comment by ivoysey** [comment]
@schmerl OK; I'm closing it now.
