### ISSUE TITLE
Use env file to specify base URLs of external BugZoo servers

### ISSUE THREAD

**Issue by ChrisTimperley** [cmu-mars/issues#52]
For now, we should use an environment file, `bugzoo.env`, hosted in the same directory as `docker-compose.yml` to provide the base URL for a single BugZoo server.

```
# bugzoo.env
BUGZOO_BASE_URL = "127.0.0.1:6060"
```

**Comment by ivoysey** [comment]
when you figure out exactly where you want that text file to be, this is the issue to update on the other repo to tell lincoln what to do. https://github.mit.edu/brass/cmu-robotics/issues/39

**Comment by ivoysey** [comment]
@ChrisTimperley is this still the plan? We need to notify Lincoln somehow of how we expect to get this information from them. I suspect that the README.md contents for CP2 are incorrect at least in the final compose; could you edit that document to make this clear and then close both issues?

**Comment by ivoysey** [comment]
I believe this is done.
