### ISSUE TITLE
Docker image for rainbow

### ISSUE THREAD

**Issue by pooyanjamshidi** [cmu-mars/issues#54]
I believe this is clear as we discussed this before. Something that is not clear from the composition point of view, whether this docker should be built on top of the current docker files for `cp1` and `cp3`?

**Comment by schmerl** [comment]
Yeah, I was thinking about that. I think that we're going to have to have

cp1_base <- cp1_rainbow <- cp1_ta

and

cp3_base <- cp3_rainbow <- cp3_ta

**Comment by ivoysey** [comment]
That was pretty much what I expected, yeah.

**Comment by ivoysey** [comment]
I think this is more or less done, modulo a question I just asked @schmerl over slack, so I'm going to close this.
