### ISSUE TITLE
CP1 stack minor errors

### ISSUE THREAD

**Issue by schmerl** [cmu-mars/issues#60]
1. When logging in to one of the cp1 controllers, the entrypoint.sh has an error: `devel/setup.sh: no such file exists`. This is probably a cut paste error from cp3.

2. cp1_base Dockerfile installs mrpt_localization, which I'm pretty sure is not needed.

**Comment by pooyanjamshidi** [comment]
@schmerl 
1. What `entrypoint.sh`? 
2. right `mrpt_localization` was not needed, fixed.

**Comment by schmerl** [comment]
This is the actual error:

`/home/mars/catkin_ws/entrypoint.sh: line 3: devel/setup.bash: No such file or directory`

**Comment by schmerl** [comment]
@pooyanjamshidi 
3. Some files that get copied (in CP1 controllers and probably CP1 base) are left owned by root. Dockerfile should be changed to chown to mars.

**Comment by schmerl** [comment]
@pooyanjamshidi 
4. When typing `roslaunch cp1_base cp1-base-test.launch` I get an error: 
```
[cp1-base-test.launch] is neither a launch file in package [cp1_base] nor is [cp1_base] a launch file name
The traceback for the exception was written to the log file
```

This might be related to 1. But, in any case it seems that the scripts to set up the path should be added to ~/.bashrc like in the other Dockerfiles.

**Comment by pooyanjamshidi** [comment]
@schmerl all errors/suggestions are fixed, so I'm closing this, reopen if needed.
