### ISSUE TITLE
Implement full charge instruction

### ISSUE THREAD

**Issue by javier-camara** [cmu-mars/issues#65]
The execution of the IG should be able to determine on its own the amount of time that it needs to recharge to get a full battery (the planner cannot tell it the amount of time that this will take as a parameter to the instruction). The set_charge should go until the battery is fully charged.

**Comment by schmerl** [comment]
The issue is that when we are generating the instructions we can not calculate the amount of time to do the charge, and so the charge instruction in the instruction interpreter (in cp1_instructions.py) should somehow wait until the battery is fully charged before returning.

**Comment by pooyanjamshidi** [comment]
Added fully charge [feature](https://github.com/cmu-mars/ig-action-server-p15/blob/759b5a8f4ca19f1a78df0a1efe251a0b696bfe0f/ig_action_server/src/cp1_instructions.py#L50). @javier-camara @schmerl please check. Note that it assumes the [configuration](https://github.com/cmu-mars/cp1_controllers/blob/master/cp1/plugins_config.json) options that are passed between backend and rainbow/planner resides in `~/cp1/plugins_config.json` as we discussed with @javier-camara.

**Comment by javier-camara** [comment]
Could you share a link to the actual json configuration file in the repo? I cannot find plugins_config.json

**Comment by pooyanjamshidi** [comment]
[Here](https://github.com/cmu-mars/cp1_controllers/blob/master/cp1/plugins_config.json).

**Comment by pooyanjamshidi** [comment]
Just out of the curiosity, in phase 1, the time for the charge was determined by the planner, no? in general we may want to have the case where just a bit of more charge is enough to finish the task/mission as we discussed at some point @javier-camara. But anyway, we have this full charge capability, but for future enhancement, we may want to think about that.

**Comment by javier-camara** [comment]
The charge time is not imposed by the planner, but the planner quantifies how much time it will take to charge as a reward. Whenever the robot has the opportunity to charge in the plan, the time will be computed based on the charge that is missing from the battery, and the charge rate. However, this information cannot be extracted from the planner in a straightforward way.
