### ISSUE TITLE
internal status to notify the TA of plan, config, and sensors

### ISSUE THREAD

**Issue by ivoysey** [cmu-mars/issues#66]
currently we always send `[]` in these three fields to Lincoln

**Comment by schmerl** [comment]
config and sensors done
at the start of the test (i.e. after /start) this should be retrieved from map_server (which I think it currently has APIs for).
In adaptive case, this will be updated once a new plan arrives -- probably post RR2

**Comment by ivoysey** [comment]
I'm moving this to RR2 IW.

**Comment by ivoysey** [comment]
I believe this is now done.
