### ISSUE TITLE
Tag P2RR2 Release branches of all repositories

### ISSUE THREAD

**Issue by schmerl** [cmu-mars/issues#68]
We should tag the repositories that we are using for RR2 release as "release/P2RR2". I am not sure how militant they are going to be about which versions we can "bug fix" during the integration week, and we should have a way to get back to what we released in three weeks time.

**Comment by ivoysey** [comment]
I'm currently planning to be fairly liberal about fixing things pre-integration week; that seemed to serve us well and not step on any toes last time, in that we ended up integrating before our technical time slot and LL was very happy about that. I think they just need to know what "The Delivery™" was, and that there needs to be one, but that doesn't mean we can't have branches ahead of master that end up getting PR'ed during IW.

**Comment by ivoysey** [comment]
Also, this is probably related to #61
