### ISSUE TITLE
Simulation time bug in TA

### ISSUE THREAD

**Issue by schmerl** [cmu-mars/issues#71]
It looks like the TA is currently giving simulation time in things that look like epochs rather than the time from simulation start. This could be a bug, and will affect evaluation.

**Comment by ivoysey** [comment]
Fascinating! When in the sequence diagram are you seeing this? The only way the TA ever reports simtime is through `rospy.Time.now().secs`. I have a worry that if you ask rospy for the time too early (before the simulation gets started) it will say something bananas and then suddenly say something reasonable; is that what you're seeing possibly?

**Comment by schmerl** [comment]
I am also seeing it in replies to /start and /perturb/nodefail

**Comment by ivoysey** [comment]
Bizarre! Must be a change in the ros API from Phase 1.

**Comment by schmerl** [comment]
I don't think it is, because I am getting the right simtime in Rainbow (well, at least things that look like 100s of seconds and not epochs!)

**Comment by schmerl** [comment]
I'm not seeing correct sim time stuff at all in testing currently. It could be the case that the first time you call rospy.Time* sets the mode (real or simulation) for all subsequent calls. Thus, if you call rospy.Time before starting ros (or maybe even before starting gazebo), then it will default to wall time for perpetuity in the TA. Coordinating this could get messy.

**Comment by ivoysey** [comment]
This may well be related to #88

**Comment by schmerl** [comment]
I believe that this is fixed now. But let's check this with output from Integration Week.

**Comment by ivoysey** [comment]
@pooyanjamshidi were you seeing similar weird times in your tests for CP1? Or was this problem limited to CP3?

**Comment by pooyanjamshidi** [comment]
@schmerl what was the fix for this?

**Comment by schmerl** [comment]
The fix was to make sure that the TA does ros_init some time after it does
roslaunch.

**Comment by pooyanjamshidi** [comment]
@ivoysey given @schmerl  fix, `CP1` is OK since we already do that in `TA`.

**Comment by ivoysey** [comment]
OK! Sounds good to me. If the times are all whacky when we see some test results we'll know what to look for, so I'm going to close this issue.
