### ISSUE TITLE
Ensure that ~/test-ready is implemented for all challenge problems

### ISSUE THREAD

**Issue by schmerl** [cmu-mars/issues#72]
To test the TA, cp3 implemented a scheme where if the parameter passed into the TA on launch does not connect to the TH, the TA will try to open it as a file emulatating a response from a fictional TH. This uncovered many syntactic and module related errors in the TA for CP3, and would be good to do for the other CPs.

**Comment by ivoysey** [comment]
@schmerl I agree that this would be good; it's lower priority for me today under getting the CP1 TA rolled out at all, but it's the obvious next step. What is the "RR2 IW" milestone you assigned this to?

**Comment by ivoysey** [comment]
@ChrisTimperley how are you faking a TH and / or doing testing? Is this relevant to you? Bradley's solution was to include a file containing a json object from the host OS for a particular ready message and to read that if you can't get to the TH.

**Comment by ChrisTimperley** [comment]
@ivoysey I've written a fairly simple client/server in Python using requests and Flask that implements all of the functionalities of the TH. (It's more of a reference implementation than a mock implementation.)

**Comment by ivoysey** [comment]
OK -- I'm going to close this issue, then, since it sounds like each CP has a way to run sans LL-written TH.
