### ISSUE TITLE
Work out utility functions

### ISSUE THREAD

**Issue by schmerl** [cmu-mars/issues#74]

**Comment by schmerl** [comment]
This is going to have to be an API change. Because the time metric is calculated based on one of the baseline runs, we do not know what that number was a priori. So, I think the API has to change to be something like:
```
{
  "utility" : {
      "time" : The sim time of the test
      "charge" : The remaining charge in the battery as a percentage of full
      "safety" : The number of collisions during the test
  }
}
```

**Comment by schmerl** [comment]
According to the evaluation, we cannot calculate the time score because it depends on another test case. But, these things are calculable by the TH from the `final-sim-time` (for time), `collisiondata` for safety and `final-charge` for charge.

**Comment by ivoysey** [comment]
@schmerl OK -- if they're derivable, that should be good enough for evaluation and save us a late-game API change. Do we want to close this issue?
