### ISSUE TITLE
In deployment, ig-interpreter does not get new instructions

### ISSUE THREAD

**Issue by schmerl** [cmu-mars/issues#76]
In the docker installation only, when Rainbow comes to issue a new instruction, the ig-interpreter gets the cancelation but it does not get the new set of instructions. This has been tested and shown to work outside docker in many instances (with the ta, without the ta, with different instructions). It just does not work in docker.

The following error appears in both the working and non-working case, indicating that this is not the cause of the problem.

```
IP socket to gaokarena:43555 (http://gaokarena:34522/): Traceback (most recent c
all last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py",
 line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused
```

**Comment by ivoysey** [comment]
@schmerl can you add the appropriate milestone to this issue?
