### ISSUE TITLE
Sharing a configuration file between CP1 backend and Planner

### ISSUE THREAD

**Issue by pooyanjamshidi** [cmu-mars/issues#77]
We decide to share a number of configuration options between CP1 backend and planner. In the future, we may need to extend this configuration file with more options, but for now, the options are only related to the battery.

```json
{
  "battery_capacity": 15121.73,
  "charging_rate": 69.9555
}
```

**Comment by pooyanjamshidi** [comment]
@schmerl @javier-camara I just added this for having these notes for documentation purposes, but we can close it right away.

**Comment by schmerl** [comment]
Let's not close it into it is done and tested.

**Comment by ivoysey** [comment]
@schmerl can you add the appropriate milestone to this issue? Or close it if you think it's been tested.

**Comment by pooyanjamshidi** [comment]
This is related to #94.

**Comment by schmerl** [comment]
@pooyanjamshidi Should we close?

**Comment by pooyanjamshidi** [comment]
Yes. @javier-camara implemented this few days ago, still running tests to make sure it's working and the options are reflected, I've seen errors like #112 but we can close this now.
