### ISSUE TITLE
Rainbow connection error

### ISSUE THREAD

**Issue by pooyanjamshidi** [cmu-mars/issues#82]
Again I see the rainbow connection issue. Note I ran this in docker environment in Ubuntu basically the same environment that we have tested before last week and it worked at that time, but again I started to see this again...
[rainbow-connection.log](https://github.com/cmu-mars/issues/files/1998801/rainbow-connection.log)

**Comment by schmerl** [comment]
Please also attach the rainbow.log. This is probably a left over from the
issue yesterday of me having to check in rainbow_interface. I suspect it is
waiting for a debugger to attach. I'm not at my computer again until
tomorrow, so I will deal with it then.

**Comment by pooyanjamshidi** [comment]
@schmerl Rainbow log here:
```
LD_LIBRARY_PATH=/home/mars/catkin_ws/devel/lib:/opt/ros/kinetic/lib:/opt/ros/kinetic/lib/x86_64-linux-gnu:/home/mars/das/prism-4.3.1-linux64/lib
java -classpath .:lib/*  -Drainbow.target=brass-p2-cp1 -Djava.rmi.server.hostname=10.0.2.2 -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=1044  org.sa.rainbow.core.RainbowMaster
Listening for transport dt_socket at address: 1044
```

**Comment by pooyanjamshidi** [comment]
@schmerl I fixed this!
