### ISSUE TITLE
No perturbations with multiple missions with repetitions throws an exception.

### ISSUE THREAD

**Issue by pooyanjamshidi** [cmu-mars/issues#83]
This is going to be frustrating, @schmerl I thought these exceptions are fixed, we previously discussed these exceptions in the rainbow log, but I see them again, here is the summary of my run, I don't think the `NullException` should be related to the docker networking thing anyway.

**Description**: This was a C case test with the mission specified in [test-ready-c.json](https://github.com/cmu-mars/cp1_base/blob/master/cp1_base/cp1/test-ready-c.json)
**Issue**: I observed several exceptions in rainbow such as `NullPointerException` in `IGWaypointAnalyzer.java` (below), more in the log file.
**Start conditions**: See description.
**Steps to reproduce**: In this case no perturbations, as I started to test `1.c` case.
```
1. Normal operation, with no perturbations and enough battery to complete the mission. 
    a. A mission with one task
    b. A mission with n tasks, no repetition in target waypoints
    c. A mission with n tasks, repetitions allowed
2. Obstacle perturbation, with enough battery to complete the mission. 
3. Battery perturbation, without obstacles again. Let's do at least two cases:
    a. Set the initial battery at the start of the test, but don't change during the test. Make it so there is not enough battery to complete the mission, but there's enough battery to get to a charging station.
    b. Perturb the battery some time during the test to suddenly make it so that the robot doesn't have enough power to complete the mission in the current configuration.
4. An obstacle and a battery perturbation.
5. Multiple perturbations of each kind.
```
**Observations**: I noticed the following exceptions, e.g.:
```
java.lang.NullPointerException
cp1_ta    | 	at org.sa.rainbow.brass.analyses.IGWaypointAnalyzer.onEvent(IGWaypointAnalyzer.java:66)
cp1_ta    | 	at org.sa.rainbow.core.ports.eseb.ESEBModelChangeBusSubscriptionPort$1.receive(ESEBModelChangeBusSubscriptionPort.java:61)
cp1_ta    | 	at org.sa.rainbow.core.ports.eseb.ESEBConnector$2.data_added_to_queue(ESEBConnector.java:317)
cp1_ta    | 	at edu.cmu.cs.able.eseb.BusDataQueue$1.dispatch(BusDataQueue.java:72)
cp1_ta    | 	at edu.cmu.cs.able.eseb.BusDataQueue$1.dispatch(BusDataQueue.java:69)
cp1_ta    | 	at incubator.dispatch.QueuedDispatch.run(QueuedDispatch.java:48)
cp1_ta    | 	at incubator.dispatch.GlobalDispatcher$DispatchRunnable.run(GlobalDispatcher.java:273)
cp1_ta    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
cp1_ta    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
cp1_ta    | 	at java.lang.Thread.run(Thread.java:748)
```

[commnad_line.log](https://github.com/cmu-mars/issues/files/1998922/commnad_line.log)
[rainbow_without_perturbation.log](https://github.com/cmu-mars/issues/files/1998923/rainbow_without_perturbation.log)

**Comment by schmerl** [comment]
You see this exception on the first task?

(Yes, frustrating - welcome to my world. Did 1.a and 1.b work?)

**Comment by pooyanjamshidi** [comment]
@schmerl Re first task, yes, everything is clear in the command line logs, that's why I sent it. Otherwise, I only would have sent the rainbow log.

As far as we see the exception, so none of them I assume would work.

**Comment by schmerl** [comment]
Pooyan:

There is a reason that we talked about doing the tests in the sequence that
you put in the issue and we discussed extensively yesterday. So, please
answer the following question, and the following question only, and only
answer "yes" or "no":

Did you try 1.a and 1.b?

Bradley.

**Comment by pooyanjamshidi** [comment]
@schmerl Yes, I did. Here are the logs:
I did not see exceptions in these two cases and the mission was successfully finished in both 1a and 1b scenarios. So I presume the `IGWaypointAnalyzer` will throw an exception in task repetition cases, but since in `cp1` we have those kinds of missions, this needs to be fixed in Rainbow, probably this is not an issue in `cp3`.

[commnad_line_c1a.log](https://github.com/cmu-mars/issues/files/2001028/commnad_line_c1a.log)
[rainbow_c1a.log](https://github.com/cmu-mars/issues/files/2001029/rainbow_c1a.log)
[commnad_line_c1b.log](https://github.com/cmu-mars/issues/files/2001027/commnad_line_c1b.log)
[rainbow_c1b.log](https://github.com/cmu-mars/issues/files/2001026/rainbow_c1b.log)

**Comment by schmerl** [comment]
OK. Good. In the template for this, you have omitted the curl command(s) for reproducing this.

**Comment by pooyanjamshidi** [comment]
@schmerl there is now.

**Comment by pooyanjamshidi** [comment]
Also corresponding [mission specification](https://github.mit.edu/brass/cmu-robotics/tree/development/cp1/ta/missions).

**Comment by schmerl** [comment]
Stop doing this. If you run another mission and you see another error then
create another issue. Do not cram multiple tests in different conditions in
the same issue. We discussed this yesterday.

**Comment by schmerl** [comment]
Rebuild cp1_rb with no cache. I think the problem is fixed, and then of course the cp1 container.

I started with your test-ready-c.json, and sent the command: `curl -H "Content-Type:application/json" -X POST -d '{}' http://localhost:8080/start`

I now get no exceptions, and the last lines in the log are:

```
cp1_ta    | [INFO] [1526309734.595128]: at-waypoint
cp1_ta    | [INFO] [1526309734.597129]: {'name': 'l8',
cp1_ta    |  'sim_time': 1526309734,
cp1_ta    |  'x': -44.81860693201117,
cp1_ta    |  'y': -11.940848461493339}
cp1_ta    | [INFO] [1526309734.599156]: The task (l5->l8) has been accomplished
cp1_ta    | [INFO] [1526309734.600020]: Accomplished 5 tasks
```
I think this means success, right?

Here is the log: [repetitions-no-perturbations-console.log](https://github.com/cmu-mars/issues/files/2001359/repetitions-no-perturbations-console.log)

**Comment by pooyanjamshidi** [comment]
@schmerl great, yes, it is a success, thanks. I will go ahead with the rest of scenarios and will update you as I go along.

**Comment by schmerl** [comment]
Please verify on your deployment before going to the other cases.

**Comment by pooyanjamshidi** [comment]
Verified.
```
cp1_ta    | [INFO] [1526312531.971411]: at-waypoint
cp1_ta    | [INFO] [1526312531.980330]: {'name': 'l8',
cp1_ta    |  'sim_time': 1526312531,
cp1_ta    |  'x': -44.84253208401683,
cp1_ta    |  'y': -11.864728392607764}
cp1_ta    | [INFO] [1526312532.005007]: The task (l5->l8) has been accomplished
cp1_ta    | [INFO] [1526312532.007858]: Accomplished 5 tasks
```

**Comment by schmerl** [comment]
Great.
