### ISSUE TITLE
Obstacle perturbation with multiple missions with repetitions throws an exception

### ISSUE THREAD

**Issue by pooyanjamshidi** [cmu-mars/issues#84]
@schmerl would you please confirm whether this is related to the networking issues in Docker? if so I can move on.

**Description**: This was a C case test with the mission specified in [test-ready-c1c.json](https://github.mit.edu/brass/cmu-robotics/blob/development/cp1/ta/missions/test-ready-c1c.json)
**Issue**: I observed an exception that might be related to the IG networking issue in Docker.
**Start conditions**: See description.
**Steps to reproduce**: 
```bash
curl -X POST "http://0.0.0.0:8080/start" -H "accept: application/json
curl -X POST "http://0.0.0.0:8080/perturb/place-obstacle" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"x\": -19.08, \"y\": 11.08}"
```

**Observations**: I noticed the following exceptions:
```
cp1_ta    | [ INFO[ERROR] [1526319157.108047632, 282.285000000]: Aborting because the robot appears to be oscillating over and over. Even after executing all recovery behaviors
cp1_ta    | [ERROR] [1526319157.114879, 282.285000]: The base failed to move, status=False
cp1_ta    | Failed!
cp1_ta    | Here
```

[commnad_line_c2a.log](https://github.com/cmu-mars/issues/files/2001981/commnad_line_c2a.log)
[rainbow_c2a.log](https://github.com/cmu-mars/issues/files/2001982/rainbow_c2a.log)

**Comment by pooyanjamshidi** [comment]
@schmerl ?

**Comment by pooyanjamshidi** [comment]
@schmerl After your fix, more exceptions appeared:
[rainbow_c2a1.log](https://github.com/cmu-mars/issues/files/2002829/rainbow_c2a1.log)
[commnad_line_c2a1.log](https://github.com/cmu-mars/issues/files/2002830/commnad_line_c2a1.log)

**Comment by pooyanjamshidi** [comment]
@schmerl as per our email, here are the logs that happened again after I rebuilt docker images all the way down to up, same exceptions and more errors like #87.
[rainbow_c2a2.log](https://github.com/cmu-mars/issues/files/2003169/rainbow_c2a2.log)
[commnad_line_c2a2.log](https://github.com/cmu-mars/issues/files/2003170/commnad_line_c2a2.log)

**Comment by pooyanjamshidi** [comment]
@schmerl logs:
[commnad_line_c2a6.log](https://github.com/cmu-mars/issues/files/2010271/commnad_line_c2a6.log)
[rainbow_c2a6.log](https://github.com/cmu-mars/issues/files/2010272/rainbow_c2a6.log)

**Comment by schmerl** [comment]
@pooyan This now seems to mostly work. Attached is the command line log (I forgot to get the rainbow log). Can you confirm that the exception has disappeared and the new IG gets done?
[repetitions-no-perturbations-console.log](https://github.com/cmu-mars/issues/files/2010572/repetitions-no-perturbations-console.log)

**Comment by pooyanjamshidi** [comment]
@schmerl  in this case, I saw adaptation for task `l2->l4`, but the next task which was `l4->l2`, it could not find a plan, see logs, basically it waited for several minutes around the obstacle and did nothing! note all the setting including perturbation same as in the description. It's good that we saw at least one adaptation for a task, but we need to succeed for the whole mission.

[commnad_line_c2a8.log](https://github.com/cmu-mars/issues/files/2011062/commnad_line_c2a8.log)
[rainbow_c2a8.log](https://github.com/cmu-mars/issues/files/2011063/rainbow_c2a8.log)

**Comment by schmerl** [comment]
How does it differ from the log I posted?

**Comment by pooyanjamshidi** [comment]
@schmerl actually in your log, I also see one task done, and one adaptation, so I didn't see the whole mission succeed, did you see it?

**Comment by schmerl** [comment]
Yes. I think I saw it succeed. It only needs one adaptation, right?

**Comment by pooyanjamshidi** [comment]
@schmerl for subsequent task also need adaptation (`l4->l2`), but it didn't find any plan and it stayed there.

**Comment by schmerl** [comment]
@pooyanjamshidi Found a potential problem with the analyzer not firing the second time. New Rainbow up. But look at #85 first before rebuilding because this might be a breaking change.

**Comment by pooyanjamshidi** [comment]
@schmerl failed:
[rainbow_c2a11.log](https://github.com/cmu-mars/issues/files/2013122/rainbow_c2a11.log)
[commnad_line_c2a11.log](https://github.com/cmu-mars/issues/files/2013123/commnad_line_c2a11.log)

**Comment by pooyanjamshidi** [comment]
@schmerl could you please take a look? the robot doesn't move and I don't see any actual plan as before, but I see `Got new plan`

[rainbow_c2a12.log](https://github.com/cmu-mars/issues/files/2014316/rainbow_c2a12.log)
[commnad_line_c2a12.log](https://github.com/cmu-mars/issues/files/2014317/commnad_line_c2a12.log)

**Comment by pooyanjamshidi** [comment]
@schmerl See:
[rainbow_c2a13.log](https://github.com/cmu-mars/issues/files/2014524/rainbow_c2a13.log)
[commnad_line_c2a13.log](https://github.com/cmu-mars/issues/files/2014525/commnad_line_c2a13.log)

**Comment by schmerl** [comment]
This seems to be working?

[command-line-log-working.log](https://github.com/cmu-mars/issues/files/2014652/command-line-log-working.log)

**Comment by ivoysey** [comment]
@pooyanjamshidi @schmerl what's the status here? is this one fixed or is it an RR3 problem?

**Comment by pooyanjamshidi** [comment]
@ivoysey can be closed, we tested it with different scenarios and it seems alright, i.e., we saw adaptation and the robot finished the mission.
