### ISSUE TITLE
Python3 causing problems with ROS

### ISSUE THREAD

**Issue by schmerl** [cmu-mars/issues#88]
Using Python3 for the TA means that if you want to do anything with ROS (e.g., listen for transforms, and perhaps even the sim time stuff), it either doesn't work or may not work. ROS is built for python2.7. How difficult would it be to change the TA to also use python2?

**Comment by schmerl** [comment]
See for example: https://github.com/ros/geometry2/issues/259. This means that the TA can't wait for the robot position to be set by the localization algorithm because it needs tf to look for a transform.

**Comment by pooyanjamshidi** [comment]
@schmerl I needed to change and find several workarounds regarding this in `cp1` backend to make it compatible with python3, I tried to convert ta to python2, but somehow I gave up...

**Comment by ivoysey** [comment]
@schmerl Honestly I'm not that sure what the exact differences are between py2 and py3. I didn't make the choice for the TA to be py3 for any grand principled reasons, but rather just because that's what swagger codegen happened to output the first time I ran it. So I'm not opposed to changing it to py2, but I have no real idea what that will entail.

**Comment by schmerl** [comment]
Can you take a look? I think at least the module system changed between two
and three. Spend a couple of hours scoping out the feasibility. Otherwise,
you'll have tow work out how to interact with ROS to do some of the things
needed in the TA.

**Comment by ivoysey** [comment]
Yeah, I'll see what I can figure out. Based on that link to an issue you included, it's probably easier to downgrade to py2 and deal with the module junk. Morally, I suspect we're really writing py2 anyway and just choosing to run it as py3.

@ChrisTimperley does this effect CP2 at all? I suspect not but you'd know better.

**Comment by ChrisTimperley** [comment]
@ivoysey it doesn't affect CP2. Also, there are a few helper packages that are designed to ease the transition from Python 2.7 to 3.x -- you might be able to use those to reduce the number of changes that you need to make. A number of the most useful ones are found here: https://docs.python.org/2/library/__future__.html

**Comment by ivoysey** [comment]
@ChrisTimperley it's the other way that we want to go, though: we have Python 3.x code but big parts of ROS seem to only work with 2.x

**Comment by ChrisTimperley** [comment]
@ivoysey, yep, I understand, but the changes that you want to make are almost the same. (Sorry for not being clear.) You just need to add the appropriate import statements to your Python 3 code to ensure that it runs on Python 2: https://docs.python.org/3/howto/pyporting.html.

For example:

```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
```

**Comment by schmerl** [comment]
@ivoysey could you try placing these at the top of cp3.py and then commenting out the import tf and the commented code in wait_for_odom and see if you can start cp3?

**Comment by ivoysey** [comment]
I'm going to move this to RR3, since it seems like things were working "well enough" by COB last week. The integration event should tell us a lot about how busted this actually is, and I'll fix this during if need be. Otherwise we should have a TH at the end of the week to hammer on and an idea of what really fails.

**Comment by schmerl** [comment]
This is still a problem, but it isn't causing any faults in my current testing so closing.

**Comment by ivoysey** [comment]
I'm going to reopen it just so that it doesn't slip through the cracks; if we're experiencing weird problems in the future I want to make sure I remember to think about this.

**Comment by schmerl** [comment]
It slipped through the cracks.
