### ISSUE TITLE
TA needs to parse the new plan

### ISSUE THREAD

**Issue by schmerl** [cmu-mars/issues#91]
When Rainbow issues a new plan (in CP3) it will send an internal/status with the following JSON:

```
{
  "status" : "PLAN",
  "msg" : "['l1', 'l2', 'l3']".
  "sim-time" : -1
}
```

This needs implemented.

**Comment by ivoysey** [comment]
fixed in https://github.mit.edu/brass/cmu-robotics/commit/da07b262aea2053d879eceed520236eee0744e65
