### ISSUE TITLE
mprt should be changed to mrpt in configruations

### ISSUE THREAD

**Issue by schmerl** [cmu-mars/issues#92]
See latest swagger file.

**Comment by schmerl** [comment]
This also needs to be changed in the TA - it refers to mpr-xxx.launch and should be mrpt-xxx.launch.

**Comment by ivoysey** [comment]
@schmerl Got it; I'll do this in just a second.

**Comment by ivoysey** [comment]
I believe this is fixed, per https://github.mit.edu/brass/cmu-robotics/commit/0602e3e40667e3c8b8e3685745e5316d1e6eaa78
