### ISSUE TITLE
Our docker images are public

### ISSUE THREAD

**Issue by pooyanjamshidi** [cmu-mars/issues#93]
@ChrisTimperley Should we be concerned about that our docker images are accessible to the world?

**Comment by schmerl** [comment]
So are our GitHub repos (except those at MIT).

Personally, I'm ok with this.

**Comment by ChrisTimperley** [comment]
I'm fine with them being public.

**Comment by ivoysey** [comment]
I believe, but am not 100% positive, that we checked with more senior folks when we set up this github org and that the reasoning would transfer over to a dockerhub org. We could check again, or just close this issue.

**Comment by ivoysey** [comment]
Since there were no objections, I'm going to close this issue.
