### ISSUE TITLE
Including objective weights in config file for flexible experimentations

### ISSUE THREAD

**Issue by pooyanjamshidi** [cmu-mars/issues#94]
@javier-camara as we discussed, I revised the config file a bit, would you please accommodate this format? Besides, I'm open if you have suggestions. Let's assume you read this config file from this path, please note the name change: `~/cp1/config.json`. 

```json
{
  "battery_capacity": 32560.0,
  "charging_rate": 69.9555,
  "utility": {
    "energy": 0.5,
    "timeliness": 0.5
  }
}
```

**Comment by ivoysey** [comment]
@pooyanjamshidi  I'm confused. Are you asking me to make a change, too? What do you mean by config file? There is no config file that I know of -- do you mean the response from `/ready/`? That snippet mentions utility for energy and timliness, which is a CP3 feature not a CP1 feature.

**Comment by pooyanjamshidi** [comment]
@ivoysey no, these config options are for backend stuff, basically shared between cp1 backend and planner, it doesn't affect TA.

**Comment by ivoysey** [comment]
@pooyanjamshidi ok, got it. thanks! :)

**Comment by pooyanjamshidi** [comment]
@schmerl would you please change the path of this config file from `~/cp1/plugins_config.json` to `~/cp1/config.json`? I guess you read this in rainbow and pass it to planner

**Comment by schmerl** [comment]
Should be done now.

**Comment by pooyanjamshidi** [comment]
@schmerl I get this exception that I think is related to this?
```
cp1_ta    | [INFO] [1526507380.115977]: Battery charge: 2.583629267871441Ah
cp1_ta    | Starting /home/mars/das/rainbow-brass/run-oracle.sh -h -w /home/mars/das/rainbow-brass brass-p2-cp1
cp1_ta    | Exception in thread "main" java.lang.NullPointerException
cp1_ta    | 	at org.sa.rainbow.brass.confsynthesis.SimpleConfigurationStore.loadFromFile(SimpleConfigurationStore.java:61)
cp1_ta    | 	at org.sa.rainbow.brass.confsynthesis.SimpleConfigurationStore.populate(SimpleConfigurationStore.java:35)
cp1_ta    | 	at org.sa.rainbow.brass.analyses.p2_cp1.EnergyConsumptionAnalyzer.initialize(EnergyConsumptionAnalyzer.java:48)
cp1_ta    | 	at org.sa.rainbow.core.RainbowMaster.initializeRainbowComponents(RainbowMaster.java:209)
cp1_ta    | 	at org.sa.rainbow.core.RainbowMaster.initialize(RainbowMaster.java:131)
cp1_ta    | 	at org.sa.rainbow.core.RainbowMaster.main(RainbowMaster.java:798)
```

**Comment by schmerl** [comment]
This is the line it crashes on:

```
JSONArray nodes = (JSONArray )jsonObject.get("configurations")

for (Object node : nodes) { ...
```
It seems that the file does not contain any `configurations`. Did the format of the file change? Does @javier-camara  know it changed?

**Comment by pooyanjamshidi** [comment]
@schmerl please see my comment in the rainbow repo.

**Comment by javier-camara** [comment]
I am a bit confused. This issue is about the small json config file to determine the battery capacity, charge rate and the preferences of the planner.

The exception you are experiencing is when we try to read the configuration list json file for the planner, which is an entirely different thing. The two main reasons why this might be failing are: (i) the file has been moved, or (ii) the format of the contents of the file have been changed.

**Comment by schmerl** [comment]
That was my fault. I thought they were the same and so changed its name in
the wrong place.

**Comment by ivoysey** [comment]
@pooyanjamshidi @javier-camara @schmerl what's the status of this issue? is it closed or does it belong in RR3?

**Comment by pooyanjamshidi** [comment]
This is now implemented and the config file is shared between backend and planner, but apparently, not all parameters are considered in the planner, such as "battery_capacity", right @javier-camara?
